package controller;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;

/**
 * This is the input handler class that tracks keyboard and mouse input for the game.
 * @author Gurangad Batth
 */
public class InputHandler implements KeyListener, MouseListener, MouseMotionListener {
    private static final int KEY_CAPACITY = 512;

    private final boolean[] keys = new boolean[KEY_CAPACITY];
    private final boolean[] mouseButtons = new boolean[4];
    private int mouseX, mouseY;

    /**
     * This method checks if a keyboard key is currently pressed.
     * @param keyCode the key code being checked
     * @return true if the key is down, false otherwise
     */
    public boolean isKeyDown(int keyCode) {
        return keyCode >= 0 && keyCode < keys.length && keys[keyCode];
    }

    /**
     * This method checks if a key is pressed and immediately clears it for one time actions.
     * @param keyCode the key code being consumed
     * @return true if the key was down before being cleared, false otherwise
     */
    public boolean consumeKeyPress(int keyCode){
        if(!isKeyDown(keyCode)){
            return false;
        }
        keys[keyCode] = false;
        return true;
    }

    /**
     * This method gets the current mouse x coordinate.
     * @return the mouse x coordinate
     */
    public int getMouseX() { 
        return mouseX; 
    }

    /**
     * This method gets the current mouse y coordinate.
     * @return the mouse y coordinate
     */
    public int getMouseY() { 
        return mouseY; 
    }

    /**
     * This method checks if the left mouse button is currently down.
     * @return true if the left mouse button is pressed
     */
    public boolean isLeftMouseDown() { 
        return mouseButtons[MouseEvent.BUTTON1]; 
    }

    /**
     * This method checks if the middle mouse button is currently down.
     * @return true if the middle mouse button is pressed
     */
    public boolean isMiddleMouseDown() { 
        return mouseButtons[MouseEvent.BUTTON2]; 
    }

    /**
     * This method checks if the right mouse button is currently down.
     * @return true if the right mouse button is pressed
     */
    public boolean isRightMouseDown() { 
        return mouseButtons[MouseEvent.BUTTON3]; 
    }

    /**
     * This method marks a mouse button as pressed.
     * @param e the mouse event generated by the press
     */
    @Override
    public void mousePressed(MouseEvent e) {
        int button = e.getButton();
        if(button < mouseButtons.length){
            mouseButtons[button] = true;
        }
    }

    /**
     * This method marks a mouse button as released.
     * @param e the mouse event generated by the release
     */
    @Override
    public void mouseReleased(MouseEvent e) {
        int button = e.getButton();
        if(button < mouseButtons.length){
            mouseButtons[button] = false;
        }
    }

    /**
     * This method updates the stored mouse position when the mouse moves.
     * @param e the mouse event generated by movement
     */
    @Override
    public void mouseMoved(MouseEvent e) {
        mouseX = e.getX();
        mouseY = e.getY();
    }

    /**
     * This method updates the stored mouse position when the mouse is dragged.
     * @param e the mouse event generated by dragging
     */
    @Override
    public void mouseDragged(MouseEvent e) {
        mouseMoved(e);
    }

    /**
     * This method marks a key as pressed.
     * @param e the key event generated by the press
     */
    @Override
    public void keyPressed(KeyEvent e) { 
        int keyCode = e.getKeyCode();
        if(keyCode >= 0 && keyCode < keys.length){
            keys[keyCode] = true;
        }
    }

    /**
     * This method marks a key as released.
     * @param e the key event generated by the release
     */
    @Override
    public void keyReleased(KeyEvent e) { 
        int keyCode = e.getKeyCode();
        if(keyCode >= 0 && keyCode < keys.length){
            keys[keyCode] = false;
        }
    }

    /**
     * This method resets every tracked keyboard key back to false.
     */
    public void resetKeys(){
        for(int i = 0; i < keys.length; i++){
            keys[i] = false;
        }
    }

    /**
     * Required empty method for the key listener interface.
     * @param e the key event generated by typing
     */
    @Override
    public void keyTyped(KeyEvent e) {}

    /**
     * Required empty method for the mouse listener interface.
     * @param e the mouse event generated by a click
     */
    @Override
    public void mouseClicked(MouseEvent e) {}

    /**
     * Required empty method for the mouse listener interface.
     * @param e the mouse event generated when the mouse enters the component
     */
    @Override
    public void mouseEntered(MouseEvent e) {}

    /**
     * Required empty method for the mouse listener interface.
     * @param e the mouse event generated when the mouse exits the component
     */
    @Override
    public void mouseExited(MouseEvent e) {}
}
